### ISSUE TITLE
Unable to obtain required cookies

### ISSUE THREAD

**Issue by JasonKing66** [alexxsalazar/Nvidia3080_BB_bot#12]
I tried to browse BB for 10 minutes. Tried different Chrome (google) account and incognito mode. The number between ~ ~ is always ||-1||. I eventually use the cookies i got on hand. How do I fix it? Should I not paste the cookies at all since it's not desirable? This morning BB released a shipment of 3080 FE and I missed it......

**Comment by YoungDrone** [comment]
I'm having the same issue. Been stuck on ~-1~-1~-1 for days. I've tried browsing for 25+ minutes in and out of incognito, won't seem to make any change to the value. Any fix to this? I want to run the bot to get in on the FE BB drops.

**Comment by alexxsalazar** [comment]
Hi. Yeah I’m not sure. I just tried it right now and was able to get the 0 within a couple seconds. For some reason you haven’t inputted the sensor data necessary for them to believe you’re an actual human browsing. Go on incognito browse, search, scroll etc. just do anything you feel a bit normally wouldn’t do. If you’re just clicking links it’s most likely not going to work. Let me know either of you need more help

**Comment by YoungDrone** [comment]
Hmm still not seeming to work. Should I try using a VPN maybe? I'm getting the -1-1~-1 value on all my devices, so maybe they flagged my IP address?

**Comment by JasonKing66** [comment]
I tried to use my school VPN in incognito mode. Still the same result for me. ||-1||. I think I will just stick with this for now.

**Comment by alexxsalazar** [comment]
No you shouldn't use a vpn imo. It should come from a residential in if anything

**Comment by YoungDrone** [comment]
Hmmm. Then yeah, I'm not sure what I'm doing wrong haha.

**Comment by alexxsalazar** [comment]
Wait I think I just realized something lol you guys are looking at the wrong part of the cookie value. It's not the end values, its the one in the middle

**Comment by alexxsalazar** [comment]
There's a screenshot in the read me take a look

**Comment by JasonKing66** [comment]
We're stupid lmao. The cookie value should be good since first try. Closing this issue now
