### ISSUE TITLE
Cards without model numbers aren't loading

### ISSUE THREAD

**Issue by mikeekert** [alexxsalazar/Nvidia3080_BB_bot#4]
Not sure if this is birdbot related, or this script.

Cards on BB's list that don't have model numbers (there's only 2 right now) come back with error's when the Tasks attempt to load the page.

**Comment by alexxsalazar** [comment]
That should have been fixed with the push last night. When did you clone project?

**Comment by mikeekert** [comment]
Ahh!

I'll try the latest build, I hadn't pulled anything for awhile now.

**Comment by alexxsalazar** [comment]
Yep haha no worries!
