### ISSUE TITLE
Timeout when getting TAS data.

### ISSUE THREAD

**Issue by keninishna** [alexxsalazar/Nvidia3080_BB_bot#7]
I've got and set the cookie data but when I run a task it just times out getting tas data. Any idea why?

[2020-10-05 12:23:37][TASK 1] Error Getting TAS Data(line 57 ConnectionError ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)))

I can manually browse to the tas link and see the json of the public key.

**Comment by alexxsalazar** [comment]
Are you by any chance using a vpn? I noticed that it happened to me with some vpn locations. What I ended up doing was just not use a vpn at all. It's not like they're going to block a residential IP.

**Comment by keninishna** [comment]
No vpn but I am doing it remotely on a hosted server. I will try it later tonight at home.

**Comment by alexxsalazar** [comment]
Yep lemme know how it goes

**Comment by keninishna** [comment]
Just managed to get it set up on my home computer and yep its working. Thanks for the help. 

Just need to figure out how to automate getting the cookies because bb tends to drop at odd hours of the night.

**Comment by alexxsalazar** [comment]
Yeah the hard part is providing their server good sensor data to give us the cookie values necessary. If you figure it out lemme know

**Comment by AdamOC3** [comment]
Is there a VPN provider that does not have the TAS issue?  I'm using NordVPN.  Program works fine without VPN connected.  While connected to VPN, I get stuck at TAS Data.  Thanks Alexx!

**Comment by alexxsalazar** [comment]
I didn’t try any others to be honest. Their data centers ips might just be flagged. Seemed like a pain to go through a bunch of vpns so I just used my residential ip. If you’re only getting one it shouldn’t be a problem

**Comment by AdamOC3** [comment]
Last question, how many seconds refresh were you running?  Thanks for posting this and being so helpful, much appreciated.  Thanks again,

**Comment by alexxsalazar** [comment]
Yep no worries. If I remember correctly I’m pretty sure I had it at every 5 seconds
