### ISSUE TITLE
Stuck at Adding to cart

### ISSUE THREAD

**Issue by JTWrenn** [alexxsalazar/Nvidia3080_BB_bot#8]
Pretty sure I have followed all the guides but when trying to add anything, I tested on a thumb drive, it fails at adding to cart.  Just sits there.

Any ideas?

**Comment by alexxsalazar** [comment]
Did you add the cookies after the 0 was present in the _abck cookie value? Also are you using a vpn or anything with data center ips?

**Comment by JTWrenn** [comment]
Yes on the cookie, and no on the VPN.

Maybe I am doing the cookies wrong.  I pulled it by using chrome, going to best buy, and then opening application, finding the cooking, and pulling the _abck Value.

Looks like this.
[cid:image001.png@01D69B46.704BF350]

**Comment by alexxsalazar** [comment]
Oh no you need more than the _abck value. Making sure the _abck has a 0 in it let’s you know that the sensor data sent has been validated. You need to copy all cookie values. You can do this by typing document.cookie in chrome dev tools console

**Comment by JTWrenn** [comment]
Oh, I think I figured it out.  I think the command might be document.cookie not cookies.  Cookies doesn’t seem to work.

Ok now on to the next issue
Error Starting Checkout (line 159 IndexError list index out of range)

Haha.

Thanks for the quick response on this, was really awesome to have such quick back and forth.

**Comment by alexxsalazar** [comment]
Haha yeah no worries. Did you accidentally add two items to cart? Sorry I’m on my phone so I can’t see what’s on line 159. Would u mind copying and pasting line 159

**Comment by JTWrenn** [comment]
From the bestbuy.py

 r = json.loads(r.text.split("var orderData = ")[1].split(";")[0])

It didn't add two items, it just added one.  Then it just throws that error over and over while it tries to checkout.

**Comment by alexxsalazar** [comment]
That's strange I've never encountered that error. Do you by any chance have the browser session open? The one you're getting your cookie values from? I've never had a problem with that call

**Comment by JTWrenn** [comment]
Oh yes, yes I do.  Maybe they are interfering with each other will try again and get back to you.

**Comment by alexxsalazar** [comment]
Oh no that shouldn't be a problem. I wanted you to go to your cart and make sure it was empty. The weird thing is that to get there the api call would have to give a 200 response. The parsing should be fine. I can look it up as soon as I get home though. Sorry about that

**Comment by JTWrenn** [comment]
No worries at all man, thanks so much for your help.  I get the same error if I empty the cart and run it again.

**Comment by JTWrenn** [comment]
Just to try it I wiped by cookies, and got a new one, and tried again.  It reliably adds to cart but then fails on checkout...wonder if it is because I am using a capital one virtual card.  I will try another one and see if it fixes it

**Comment by JTWrenn** [comment]
Well getting further.  Figured out that I was not using incognito to pull the cookie, and it was causing issues because I was logged in.  Did some strange things.  Now it got past it and hit a Payment Failed error.  Maybe an issue with the cap one virtual card now.  Will keep trying things

**Comment by JTWrenn** [comment]
Oh, got it working!!

I used a mastercard debit card instead of the virtual card from cap one and it went through!  Thanks man.  Will have to try a few things for real now:)

**Comment by alexxsalazar** [comment]
Ah sweet, yeah I'm guessing it's the card at that point. I only ever used a privacy.com virtual card. Im guessing that since its a capital one card it's making you verify through 3dsecure

**Comment by alexxsalazar** [comment]
Oh nice! Sweet glad you got it working. Sorry about the headache it might've caused. Hope you're able to get a card for yourself! Good Luck!

**Comment by JTWrenn** [comment]
What are you talking about man!  This is super awesome!  Thanks so much for this.

**Comment by AdamOC3** [comment]
Is it really necessary to regenerate cookie information every couple hours?  Thanks Alexx!!!

**Comment by alexxsalazar** [comment]
> Is it really necessary to regenerate cookie information every couple hours?  Thanks Alexx!!!

Yeah sadly if you find a way around this lemme know

**Comment by JTWrenn** [comment]
If anyone is willing to do some timing checks on this it would be great.  Knowing the time frame would be a big deal.  What are you thinking Alex?  Like every 4 hours?

**Comment by AdamOC3** [comment]
What happens if you don't regenerate the cookie?  Check out will fail when item finally comes in stock?  Sorry for dumb question.

**Comment by alexxsalazar** [comment]
Yeah no worries. And don’t sweat it not a dumb question. Yeah checkout would just fail. As for time frame JT I believe it’s around 4-5 hours. I didn’t do much testing on that though. I just had it on while I used my pc and replaced it every like 4 hours or so
